checkstyle in verify

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,19 +44,19 @@ jobs: # a collection of steps
       - run: mvn package # run the actual tests
 
 
-      # Checkstyle
-      - run:
-          name: checkstyle
-          command: |
-            mvn checkstyle:checkstyle
-            errors=$(cat ./target/site/checkstyle.rss | grep -i "errors:" | sed 's/Errors://' | sed 's/,//' | sed 's/ //')
-            echo $errors
-            if [[ $errors > 2524 ]]; then echo "too many Checkstyle errors"; exit 1; fi
-      # 2524 es el valor que elegimos como max de errores para que no falle
+#      # Checkstyle
+#      - run:
+#          name: checkstyle
+#          command: |
+#            mvn checkstyle:checkstyle
+#            errors=$(cat ./target/site/checkstyle.rss | grep -i "errors:" | sed 's/Errors://' | sed 's/,//' | sed 's/ //')
+#            echo $errors
+#            if [[ $errors > 2524 ]]; then echo "too many Checkstyle errors"; exit 1; fi
+#      # 2524 es el valor que elegimos como max de errores para que no falle
 
       # PMD, CPD, FindBugs and Jacoco
       - run:
-          name: verify PMD-FindBugs-Jacoco
+          name: verify Checkstyle-PMD-FindBugs-Jacoco
           command: mvn clean verify
 
       - store_test_results: # uploads the test metadata from the target/surefire-reports directory so that it can show up in the CircleCI dashboard.
